apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: mpstore-catalogo-api:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db-service
spec:
  selector:
    app: catalog-db
  ports:
    - protocol: TCP
      port: 1433
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog-db-statefulset
spec:
  replicas: 3
  serviceName: catalog-db-service
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: catalog-db
          image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: MSSQL_SA_PASSWORD
              value: "DevOps@01-2024"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: "/mssql/data"
              name: sqldata-storage
